version: '3.8'

services:
  backend:
    build:
      context: ./mars-rover-backend
    image: mars-rover-backend
    ports:
      - "8000:80"
    volumes:
      - ./mars-rover-backend:/var/www/html
    depends_on:
      - mysql

  frontend:
    build:
      context: ./mars-rover-frontend
    image: mars-rover-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./mars-rover-frontend:/app:cached
      - /app/node_modules        # <--- ignoramos el node_modules local
    working_dir: /app
    command: npm run dev -- --host

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
